import urllib.request
import json
import time
import sys

# Selected endpoints from apilist.md required for Bill analysis
ENDPOINTS = {
    "bills": "https://data.parliament.scot/api/bills",
    "billstages": "https://data.parliament.scot/api/billstages",
    "billtypes": "https://data.parliament.scot/api/billtypes",
    "billstagetypes": "https://data.parliament.scot/api/billstagetypes",
    "members": "https://data.parliament.scot/api/members",
    "memberparties": "https://data.parliament.scot/api/memberparties",
    "parties": "https://data.parliament.scot/api/parties",
    "committees": "https://data.parliament.scot/api/committees",
    "personcommitteeroles": "https://data.parliament.scot/api/personcommitteeroles",
    "committeeroles": "https://data.parliament.scot/api/committeeroles",
    "motionsquestionsanswersmotions": "https://data.parliament.scot/api/motionsquestionsanswersmotions",
    "votesmotion": "https://data.parliament.scot/api/votesmotion?year=2024",
    "orsplenarymeeting": "https://data.parliament.scot/api/orsplenarymeeting?year=2024",
    "orscommitteemeeting": "https://data.parliament.scot/api/orscommitteemeeting?year=2024"
}

def query_url(url):
    req = urllib.request.Request(url, headers={'User-Agent': 'Academic Endpoint Explorer'})
    start = time.time()
    try:
        with urllib.request.urlopen(req, timeout=20) as res:
            data = json.loads(res.read().decode('utf-8'))
            elapsed = time.time() - start
            return data, elapsed, None
    except Exception as e:
        elapsed = time.time() - start
        return None, elapsed, str(e)

def audit_endpoint(name, base_url):
    print(f"Auditing {name}...", flush=True)
    
    # 1. Fetch small sample
    sample_url = f"{base_url}&$top=2" if "?" in base_url else f"{base_url}?$top=2"
    payload, elapsed, err = query_url(sample_url)
    
    if err:
        return {
            "name": name,
            "status": "FAIL",
            "latency": elapsed,
            "error": err,
            "volume": "Unknown",
            "pagination": "Unknown",
            "schema": []
        }
        
    records = payload if isinstance(payload, list) else [payload]
    volume = len(records)
    
    # 2. Check if $count is supported (some return count as string or json, some 404/fail)
    count_url = base_url.split("?")[0] + "/$count"
    count_val, _, count_err = query_url(count_url)
    
    if not count_err and count_val is not None:
        volume = count_val
    else:
        # If count fails, try querying the full endpoint (if small) or using array size
        # We will state if count is not supported
        volume = "OData $count Unsupported"

    # 3. Verify pagination behavior: compare top=1 vs top=1 & skip=1
    pag_url1 = f"{base_url}&$top=1" if "?" in base_url else f"{base_url}?$top=1"
    pag_url2 = f"{base_url}&$top=1&$skip=1" if "?" in base_url else f"{base_url}?$top=1&$skip=1"
    
    p1, _, _ = query_url(pag_url1)
    p2, _, _ = query_url(pag_url2)
    
    ignores_pagination = False
    if p1 and p2 and isinstance(p1, list) and isinstance(p2, list) and len(p1) > 0 and len(p2) > 0:
        # Check first key's value to see if identical
        k = list(p1[0].keys())[0]
        if p1[0][k] == p2[0][k]:
            ignores_pagination = True
            
    pagination_desc = "Ignores $skip (Infinite Loop Risk)" if ignores_pagination else "Supported"
    
    schema_fields = []
    if len(records) > 0:
        for k, v in records[0].items():
            t = "null" if v is None else type(v).__name__
            schema_fields.append(f"{k} ({t})")

    return {
        "name": name,
        "status": "OK",
        "latency": elapsed,
        "volume": volume,
        "pagination": pagination_desc,
        "schema": schema_fields[:12], # Truncate schema display to first 12 fields
        "url": base_url
    }

def main():
    report_lines = [
        "# Academic API Exploration Report: GB-SCT",
        "",
        "This report is dynamically generated by `scripts/explore_endpoints.py` directly from the live Scottish Parliament OData service. It documents the exact volume, pagination support, latency, and sample schemas for each endpoint we need.",
        "",
        "| Endpoint | Status | Latency (s) | Estimated Volume / Count | Pagination ($skip) | Sample Schema (Partial) |",
        "|---|---|---|---|---|---|",
    ]
    
    for name, url in ENDPOINTS.items():
        res = audit_endpoint(name, url)
        if res["status"] == "OK":
            schema_str = ", ".join(res["schema"])
            if len(res["schema"]) >= 12:
                schema_str += "..."
            report_lines.append(
                f"| `{res['name']}` | OK | {res['latency']:.2f}s | {res['volume']} | {res['pagination']} | {schema_str} |"
            )
        else:
            report_lines.append(
                f"| `{res['name']}` | **FAILED** | {res['latency']:.2f}s | N/A | N/A | Error: {res['error']} |"
            )
            
    with open("docs/api_exploration.md", "w") as f:
        f.write("\n".join(report_lines))
    print("\nAudit complete! Report written to docs/api_exploration.md")

if __name__ == "__main__":
    main()
